version: "3.9"

services:
  app:
    build: .
    container_name: library-app
    ports:
      - "${APP_PORT:-8000}:8000"
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: >-
        postgresql+psycopg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${DB_HOST}:${DB_PORT}/${POSTGRES_DB}
      REDIS_HOST: ${REDIS_HOST}

  db:
    image: postgres:16
    container_name: library-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${DB_PORT:-5432}:5432" # for pgadmin connection
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    build: ./infra/redis
    container_name: library-redis
    # No need to expose 6379 unless debugging from host
    # ports:
    #   - "6379:6379"

volumes:
  pgdata:
