version: "3.9"

services:
  app:
    build: .
    container_name: library-app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: postgresql+psycopg://123456:postgres@db:5432/library_app
      REDIS_HOST: redis

  db:
    image: postgres:16
    container_name: library-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: library_app
      ports:
        - "5432:5432" # for pgadmin connection
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    build: ./infra/redis
    container_name: library-redis
    # No need to expose 6379 unless debugging from host
    # ports:
    #   - "6379:6379"

volumes:
  pgdata:
